---
heat_template_version: wallaby

description: > 
  HOT template that creates all servers for guacamole

parameters:
  environment:
    type: string
    description: Deployment env
  network:
    type: string
    description: Network ID
  v4_subnet:
    type: string
    description: ID of v4 subnet
  v6_subnet:
    type: string
    description: ID of v4 subnet
  key_name:
    type: string
    description: SSH key for all servers
  os_image:
    type: string
    description: Defaul OS for all servers
  external_net:
    type: string
    description: ID or name for floating IP pool
  sec_groups:
    type: comma_delimited_list
    description: Common security groups
  sec_groups_web:
    type: comma_delimited_list
    description: Security groups for web traffic
  zabbix_servers:
    type: string
    description: String of Zabbix Server IPs. Comma-separated
  admin_email:
    type: string
    description: Admin email for Apache config
  ntnu_admin_group:
    type: string
    description: BAS group for server admins, allowing ssh and sudo
  rproxy_ip:
    type: string
    description: Static IPv4 for reverse proxy
  rproxy_flavor:
    type: string
    description: Flavor for reverse proxy
  tls_key:
    type: string
    description: Private key for TLS cert
  tls_cert:
    type: string
    description: TLS certificate
  cert_chain:
    type: string
    description: Certificate for CA
  guacamole_ip:
    type: string
    description: Static IPv4 for guacamole server
  guacamole_flavor:
    type: string
    description: Flavor for guacamole server
  guacamole_fqdn:
    type: string
    description: FQDN for guacamole web access
  guacamole_version:
    type: string
    description: Version of Guacamole
  db_ip:
    type: string
    description: Static IPv4 for MySQL server
  db_flavor:
    type: string
    description: Flavor for MySQL server
  db_root_password:
    type: string
    description: MySQL root password
  db_guacamole_password:
    type: string
    description: MySQL guacamole_user password
  ldap_host:
    type: string
    description: LDAP host to auth with
  ldap_user_base:
    type: string
    description: OU with users
  ldap_group_base:
    type: string
    description: OU with groups
  ldap_group_search_filter:
    type: string
    description: Search filter for groups
  ldap_member_attribute:
    type: string
    description: LDAP attribute for group members
  ldap_member_attribute_type:
    type: string
    description: LDAP attribute type for group members
  ldap_user_attributes:
    type: string
    description: Which LDAP attributes to import for a user

resources:
  rproxy:
    type: lib/rproxy-server.yaml
    properties:
      server_name: { list_join: ['-', [ { get_param: environment }, guac-rproxy ]]}
      image: { get_param: os_image }
      flavor: { get_param: rproxy_flavor }
      key_name: { get_param: key_name }
      network: { get_param: network }
      ip: { get_param: rproxy_ip }
      v4_subnet: { get_param: v4_subnet }
      v6_subnet: { get_param: v6_subnet }
      sec_groups:
        list_join: [',', {get_param: sec_groups}, {get_param: sec_groups_web}]
      zabbix_servers: { get_param: zabbix_servers }
      external_net: { get_param: external_net }
      admin_email: { get_param: admin_email }
      ntnu_admin_group: { get_param: ntnu_admin_group }
      guacamole_host: { get_param: guacamole_ip }
      guacamole_fqdn: { get_param: guacamole_fqdn }
      tls_key: { get_param: tls_key }
      tls_cert: { get_param: tls_cert }
      cert_chain: { get_param: cert_chain }

  guacamole:
    type: lib/guacamole-server.yaml
    properties:
      server_name: { list_join: ['-', [ { get_param: environment }, guacamole ]]}
      image: { get_param: os_image }
      flavor: { get_param: guacamole_flavor }
      key_name: { get_param: key_name }
      network: { get_param: network }
      ip: { get_param: guacamole_ip }
      v4_subnet: { get_param: v4_subnet }
      v6_subnet: { get_param: v6_subnet }
      sec_groups: { get_param: sec_groups }
      zabbix_servers: { get_param: zabbix_servers }
      ntnu_admin_group: { get_param: ntnu_admin_group }
      db_ip: { get_param: db_ip }
      db_password: { get_param: db_guacamole_password }
      rproxy_ip: { get_param: rproxy_ip }
      guacamole_version: { get_param: guacamole_version }
      ldap_host: { get_param: ldap_host }
      ldap_user_base: { get_param: ldap_user_base }
      ldap_group_base: { get_param: ldap_group_base }
      ldap_group_search_filter: { get_param: ldap_group_search_filter }
      ldap_member_attribute: { get_param: ldap_member_attribute }
      ldap_member_attribute_type: { get_param: ldap_member_attribute_type }
      ldap_user_attributes: { get_param: ldap_user_attributes }

  guac-db:
    type: lib/db-server.yaml
    properties:
      server_name: { list_join: ['-', [ { get_param: environment }, guac-db ]]}
      image: { get_param: os_image }
      flavor: { get_param: db_flavor }
      key_name: { get_param: key_name }
      network: { get_param: network }
      ip: { get_param: db_ip }
      v4_subnet: { get_param: v4_subnet }
      v6_subnet: { get_param: v6_subnet }
      sec_groups: { get_param: sec_groups }
      zabbix_servers: { get_param: zabbix_servers }
      ntnu_admin_group: { get_param: ntnu_admin_group }
      db_root_password: { get_param: db_root_password }
      db_guacamole_password: { get_param: db_guacamole_password }
      guac_ip: { get_param: guacamole_ip }
